### ISSUE TITLE
[Feature Request] Export Attributes & Tags for Non Project Formats

### ISSUE THREAD

**Issue by Kalaschnik** [NaturalIntelligence/imglab#186]
I just tested your application and it really suits my purposes. However, I realized after exporting my work in a non-project format (e.g., JSON, XML), I miss all the attributes and tags I defined. I’m aware of #154 and #141; yet, both are closed with no actual answer.
In other words, I don’t see how I can use your application when there is no way to export my annotations in a typical exchange format. Moreover, the actual project format (.nimn), does only contain the attribute keys and not their corresponding values.

Do I miss an actual way to get the data out from the app?

Thanks for the insight on this issue!

**Comment by amitguptagwl** [comment]
I started with nimn format as it is binary format and much smaller than JSON. However, due to my engagement with other, I'm not able to give any time to this project. Hence, I'm expecting contributors I can guide.

Coming back to your concern. Different different projects need data in different formats. imglab supports to export data in 
* dlib XML
* dlib pts
* Pascal VOC
* COCO

Definitely you'll lose some information which is not supported by particular format. Hence, I've given the feature to export project file in nimn or json format that you can load back to continue your work. Your work also get saved in your browser local storage. So if you open imglab without removing browser cache (storage to be specific) and with the same images then you can see all the annotation detail again.

I hope this will help.

**Comment by Kalaschnik** [comment]
Thanks for pointing out the local storage. I was not looking there but that's actually the information I was looking for :)
