### ISSUE TITLE
Show the list of contributors on README

### ISSUE THREAD

**Issue by amitguptagwl** [NaturalIntelligence/imglab#49]
better if it is automated.

**Comment by rohitkrishna094** [comment]
I'd like to try this. Is it ok, if I just create a new js file under js folder called `contributors.js` and add a script to package.json called say `generateContributors`? Then we can run `npm generateContributors` and that alone should update readme file(and add new contributors to the end). You could later on set up a cron job to run this `npm generateContributors` script to update as and when a new contribution occurs or on a daily or a weekly basis(as I believe from their documentation, the github api takes some time to update new contributions since they are cached).

**Comment by amitguptagwl** [comment]
There are many npm packages already available to do this. But it'll become a manual approach in this way.

Check contribution list on [Fast XML Parser](https://github.com/NaturalIntelligence/fast-xml-parser). Opencollective API let you show list of contributors automatically, if you're register there. But that can be happened only when we've 100 stars on this repo.

I couldn't find other solution.

BTW Didn't you sleep today?

**Comment by rohitkrishna094** [comment]
Haha, well I did sleep.  :P

No idea about opencollective. I guess there are other APIs out there, but I thought this was simple enough to do it with vanilla nodejs. 

Either way, if anyone else would like to take this issue up, they can. :)

**Comment by amitguptagwl** [comment]
I thought to implement opencollective API but it needs server to render SVG. Hence I was looking for an alternative.

**Comment by rohitkrishna094** [comment]
True, without a server we can't do much. I just closed my PR. Let me reopen it and you can decide to merge it after maybe waiting for few days in case someone comes up with another alternative.

**Comment by amitguptagwl** [comment]
Merged the PR. Let this issue be open for next few days for more solutions.
